version: '2'

services:

  nginx:
    image: nginx:1.15.8-alpine
    depends_on:
      - backend
    volumes:
      - ./static:/static
      - ./docker/conf.nginx:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  postgresql:
    image: postgres:11.1-alpine
    env_file: ./.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: {context: ./, dockerfile: docker/Dockerfile}
    volumes:
      - ./static:/static
    env_file:
      - ./.env
    depends_on:
      - postgresql

