# Generated by Django 2.2.7 on 2019-11-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='gid',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Gid'),
        ),
    ]
